DELETE FROM USER;
INSERT INTO  USER (USERID, ROLEID, MANAGERID, USERNAME, LOGIN, PASSWORD, DELETED, BONUS) VALUES (0, 0, 0, 'FIO admin', 'admin', '1234', FALSE, 0);
INSERT INTO  USER (USERID, ROLEID, MANAGERID, USERNAME, LOGIN, PASSWORD, DELETED, BONUS) VALUES (1, 1, 0, 'FIO manager1', 'manager1', '1234', TRUE, 0);
INSERT INTO  USER (USERID, ROLEID, MANAGERID, USERNAME, LOGIN, PASSWORD, DELETED, BONUS) VALUES (2, 1, 0, 'FIO manager2', 'manager2', '1234', FALSE, 0);